# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SinaWeiBo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SinaWeiBo

    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'SnapKit'
    pod 'SVProgressHUD'

  target 'SinaWeiBoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SinaWeiBoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
